name: m3u_parser
description: m3u parser
version: 1.0.0
homepage: https://github.com/yuri-voloshyn/m3u-parser

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
